### ISSUE TITLE
Showing the outcomes of the tool

### ISSUE THREAD

**Issue by SaskiaKaas** [daankoning/ArbitrageFinder#1] opened 2023-12-22 08:39 UTC
It is not really clear when I want to display the results of the tool. When I use the --unformatted the result is displayed as follows. 
![WithUnformatted](https://github.com/daankoning/ArbitrageFinder/assets/124439687/055bdaf7-2137-4395-8ab3-1a1deec2be40)

If I leave out the --unformatted then the results are displayed as follows. 
![WithoutUnformatted](https://github.com/daankoning/ArbitrageFinder/assets/124439687/21909448-4119-4fe3-8efd-8b2a03a24dac)

Is this normal that the outcomes are displayed like this, and which of the 2 methods is best recommended?
I also have a question about how I can see exactly how much money I should bet on each odd so that I am sure to make a profit.

**Comment by daankoning** [comment] 2024-01-05 20:08
Hi, I think this is an issue with your API key. As you can see on the last line, it says that you have reached your request quota. 

I will now close this issue, if you think that the problem is caused by anything else please feel free to comment on this issue again.

**Closed by daankoning** 2024-01-05 20:08 UTC
